### ISSUE TITLE
Deployment errors

### ISSUE THREAD

**Issue by virtualex-itv** [lamw/vsphere-with-tanzu-nsxt-automated-lab-deployment#17]
Deployment completes but I receive the following errors towards the end of the deployment.   Have tried redeploying several times with the same result.  T0 uplink interface doesn't get created and static route does not get added.

**deployed using: PowerShell 7.1.0 | PowerCLI 12.1.0**

```
OperationStopped: C:\Users\Administrator\Desktop\vghetto\vghetto-vsphere-with-kubernetes-external-nsxt-lab-deployment.ps1:1393
Line |
1393 |          $t0GatewayInterface = $t0GatewayInterfacePolicyService.update …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A server error occurred: 'com.vmware.vapi.std.errors.invalid_request': . Check
     | $Error[0].Exception.ServerError for more details.

[12-17-2020_11:25:48] Adding Static Route on T0 Gateway Interface from 0.0.0.0/0 to 192.168.1.132 ...
OperationStopped: C:\Users\Administrator\Desktop\vghetto\vghetto-vsphere-with-kubernetes-external-nsxt-lab-deployment.ps1:1414
Line |
1414 |          $staticRoute = $staticRoutePolicyService.patch($T0GatewayName …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A server error occurred: 'com.vmware.vapi.std.errors.invalid_request': . Check
     | $Error[0].Exception.ServerError for more details.
```

**Comment by dafonehacker** [comment]
Have you found a solution to this?

**Comment by virtualex-itv** [comment]
It may be related to the powershell version.  I believe I got it to work by using powershell 7.0.0 instead of 7.1.0

**Comment by dafonehacker** [comment]
In case anyone is interested I got it working in my configuration. See my comment on the post:
https://www.virtuallyghetto.com/2020/04/automated-vsphere-7-and-vsphere-with-kubernetes-lab-deployment-script.html

"
Actually I think I just got it working using the 3.1.0 le version. It says the workload management cluster is running but can’t test it right now, will come back to that later…
What I did was set MTU to 1600 on everything I could (all VDS’s, T0interface…) like described in this writeup: https://itnext.io/nested-vsphere-7-and-kubernetes-lab-deployment-explained-f9bfca0112f5

And also did the accept promiscuous mode and forged transmits on everything I could find in both the nested and native vsphere instance.

To manually configure the part of the t0 gateway that the script failed on (not the ones you just posted but the ones before that) I did this in the NSX T manager gui:
click on networking -> T0 gateway (there should already be one)
Edit the gateway
Go to interfaces
add
name: default
type: external
ipaddress/mask: what you set in the variables (192.168.0.14/24 in my case)
connected to segment: pacific-segment
edge node: the edge node
MTU: 1600

Then save and close the interface editing part
Go to routing -> static routes
name default network 0.0.0.0/0 next hop 192.168.0.1(your internet gateway)
"
So I ignored the 2 errors, did the steps outlined above and was then successful enabling the workload management feature...
(using Powershell 7.0.0 & PowerCLI 12.0.0)

**Comment by lamw** [comment]
Actually just ran into this myself and debugged a bit. Its not related to the version of PowerShell, but rather it looks like using NSX-T 3.x, there were some changes to the APIs. 

What's failing is the lookup of the T0 Interface scope:

```
$scopePath = ($t0GatewayInterfacePolicyService.list($T0GatewayName,"default").results | where {$_.resource_type -eq "Tier0Interface"} | Select -First 1).path
```

However, the failure is occurring because the T0 Interface does not exists and hence the lookup wasn't successful. 

In looking at the code and what the UI does, it looks like with NSX-T 3.x, instead of using the `transport_node_id` to identify the Edge Node Member as my code does:

```
$edgeClusterMember = ($edgeClusterService.get($edgeCluster.id)).members.transport_node_id
```

It looks like it now expects the `member_index` which is 0 for single Edge Node within Edge Cluster. Weird thing is the API docs still show using TN ID ... https://vdc-download.vmware.com/vmwb-repository/dcr-public/9e1c6bcc-85db-46b6-bc38-d6d2431e7c17/30af91b5-3a91-4d5d-8ed5-a7d806764a16/api_includes/method_CreateOrReplaceTier0Interface.html

So the actual fix is simply update `$edgeClusterMember` logic to the following:

```
$edgeClusterMember = ($edgeClusterService.get($edgeCluster.id)).members.member_index
```

**Comment by lamw** [comment]
This is now fixed
